### PR TITLE
SLING-9593: Abstract out binary handling to allow plugging of different stores

### PR DESCRIPTION
**Pull request by amit-jain**
- Introduced an interface BinaryStore and JcrBinaryStore as the default implementation storing the binaries in JCR with no change in the existing strategy of storing based on size.

### CODE REVIEW

**Comment by cschneider** [comment]
Do you think we need the binary store to be generic?

Could we just make it like this ?
public interface BinaryStore {
    InputStream get(String url) throws IOException;
    String store(InputStream binaryStream) throws IOException;
}

**Comment by amit-jain** [comment]
Yes, the simple apis won't work with jcr at least looks like cleanly. To have more clean implementation for support of default JCR as well as other stores please see implementation at https://github.com/apache/sling-org-apache-sling-distribution-journal/pull/54.

**Comment by cschneider** [comment]
I know we are currently using the ResourceResolver in String store(ResourceResolver resolver, DistributionPackage disPkg). I am not sure it is necessary though. 
PackageRepo already has a reference to ResourceResolverFactory. So we could create our own ResourceResolver to store the package. 
I also don't think we strictly need to store the packages by package type. If we store them just in one path we do not need to get the pkg type. 
So I think with a little more effort we could remove the need for ResourceResolver and for DistributionPackage. 
As we introduce a possibly long lasting API with BinaryStore I think it is worth the additional effort.

One thing to consider is of course how to make the transition. If we change the way we store we might leave some old packages behind. As we use the PackageRepo only very seldomly I think we could just leave possible old packages behind and clean them up manually if needed.

**Comment by tmaret** [comment]
It makes sense to avoid ResourceResolver as it's tied to the Sling repository and we will likely store packages not managed by Sling (e.g. Azure blobs, S3, etc.).

What is the proposed alternative API exactly ?

Regarding the transition, storing the packages under a different path would indeed only affect the collection of the packages. It would not impact importing the packages because those are resolved at the JCR level with references pointing to the blob store. As pointed out by @cschneider, barely any packages are stored in JCR anyway, we added that path for compatibility reason, knowing it'd be barely used. Our 1500+ cloud environment exhibit 0 occurrence over last week for instance.

**Comment by cschneider** [comment]
I created a PR to change the PackageRepo so it does not need ResourceResolver and DistributionPackage anymore. https://github.com/apache/sling-org-apache-sling-distribution-journal/pull/55

The simpler interface would be :
    public interface BinaryStore {
        InputStream get(String id) throws IOException;
        String put(String id, InputStream is, long length) throws IOException;
    }

In comparison to the interface I originally thought of, Amit added the length parameter which makes sense as Azure blob store needs it.

**Comment by tmaret** [comment]
Content-Length header is indeed useful to upload a size delimited payloads efficiently to an HTTP API. It is true for S3 as well. It makes sense to be in the API.

With the addition of the `length` and the `identifier` parameters, the API looks good to me.

**Comment by cschneider** [comment]
Yes you are rifght, I forgot about "id". It also makes sense to add it as it makes the API idempotent.

**Comment by amit-jain** [comment]
@cschneider @tmaret Have updated the PR to use the simplified interface.

**Pull request merged**
